#!/bin/bash

# Carrots Environment Setup Script
# This script helps configure database credentials for local development

set -e

echo "🥕 Carrots Environment Setup"
echo "============================"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if we're in the project root
if [ ! -f "docker-compose.yml" ]; then
    echo -e "${RED}❌ Error: This script must be run from the project root directory${NC}"
    exit 1
fi

# Read docker-compose.yml to get default credentials
DEFAULT_USER="carrots"
DEFAULT_PASSWORD="carrots_password"
DEFAULT_DB="carrots_dev"
DEFAULT_PORT="5432"

echo "This script will set up your environment variables for local development."
echo ""
echo -e "${YELLOW}Current Docker Compose Configuration:${NC}"
echo "  Database User: $DEFAULT_USER"
echo "  Database Name: $DEFAULT_DB"
echo "  Port: $DEFAULT_PORT"
echo ""

# Ask if user wants to use Docker credentials or set custom ones
echo "Choose an option:"
echo "  1) Use Docker Compose credentials (recommended for local development)"
echo "  2) Set custom credentials"
echo ""
read -p "Enter your choice (1 or 2) [1]: " choice
choice=${choice:-1}

if [ "$choice" = "1" ]; then
    # Use Docker credentials
    DB_USER="$DEFAULT_USER"
    DB_PASSWORD="$DEFAULT_PASSWORD"
    DB_NAME="$DEFAULT_DB"
    DB_PORT="$DEFAULT_PORT"
    echo -e "${GREEN}✓ Using Docker Compose credentials${NC}"
elif [ "$choice" = "2" ]; then
    # Custom credentials
    echo ""
    echo "Enter custom database credentials:"
    read -p "Database user [$DEFAULT_USER]: " DB_USER
    DB_USER=${DB_USER:-$DEFAULT_USER}
    
    read -sp "Database password [$DEFAULT_PASSWORD]: " DB_PASSWORD
    echo ""
    DB_PASSWORD=${DB_PASSWORD:-$DEFAULT_PASSWORD}
    
    read -p "Database name [$DEFAULT_DB]: " DB_NAME
    DB_NAME=${DB_NAME:-$DEFAULT_DB}
    
    read -p "Database port [$DEFAULT_PORT]: " DB_PORT
    DB_PORT=${DB_PORT:-$DEFAULT_PORT}
    
    echo -e "${GREEN}✓ Using custom credentials${NC}"
else
    echo -e "${RED}❌ Invalid choice${NC}"
    exit 1
fi

# Create DATABASE_URL
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@localhost:${DB_PORT}/${DB_NAME}"

# Optional: Ask for JWT secret
echo ""
read -p "Set custom JWT secret? (y/N) [N]: " set_jwt
set_jwt=${set_jwt:-N}

if [[ "$set_jwt" =~ ^[Yy]$ ]]; then
    read -sp "Enter JWT secret: " JWT_SECRET
    echo ""
else
    JWT_SECRET="your-super-secret-jwt-key-change-this-in-production"
fi

# Optional: Ask for OpenAI API key
echo ""
read -p "Set OpenAI API key? (y/N) [N]: " set_openai
set_openai=${set_openai:-N}

if [[ "$set_openai" =~ ^[Yy]$ ]]; then
    read -p "Enter OpenAI API key: " OPENAI_API_KEY
else
    OPENAI_API_KEY="sk-your-openai-api-key-here"
fi

# Create .env file in backend directory
ENV_FILE="backend/.env"

echo ""
echo -e "${YELLOW}Creating $ENV_FILE...${NC}"

cat > "$ENV_FILE" << EOF
# Database configuration
# Auto-generated by setup-env.sh on $(date)
DATABASE_URL="$DATABASE_URL"

# JWT Secret for authentication
JWT_SECRET="$JWT_SECRET"

# OpenAI API Key (optional, for NLP features)
OPENAI_API_KEY="$OPENAI_API_KEY"

# Server configuration
PORT=3001
NODE_ENV=development
CORS_ORIGIN="http://localhost:3000"
EOF

echo -e "${GREEN}✓ Environment file created successfully!${NC}"
echo ""
echo "📋 Next steps:"
echo ""

if [ "$choice" = "1" ]; then
    echo "  1. Start Docker Compose:"
    echo "     ${YELLOW}docker compose up -d${NC}"
    echo ""
    echo "  2. Run database migrations:"
    echo "     ${YELLOW}cd backend && npm run prisma:migrate:dev${NC}"
    echo ""
    echo "  3. (Optional) Seed demo data:"
    echo "     ${YELLOW}npm run prisma:demo-seed${NC}"
else
    echo "  ${RED}⚠️  Note: You're using custom credentials.${NC}"
    echo "  Make sure your PostgreSQL server is running with these credentials."
    echo ""
    echo "  1. Ensure PostgreSQL is running"
    echo "  2. Create database if needed: ${YELLOW}createdb $DB_NAME${NC}"
    echo "  3. Run migrations: ${YELLOW}cd backend && npm run prisma:migrate:dev${NC}"
    echo "  4. (Optional) Seed demo data: ${YELLOW}npm run prisma:demo-seed${NC}"
fi

echo ""
echo -e "${GREEN}✅ Setup complete!${NC}"
